// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Categorias documents */
interface CategoriesDocumentData {
  /**
   * Nome da CAtegoria field in *Categorias*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.categoryName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  categoryName: prismic.KeyTextField;
  /**
   * Imagem da Categoria field in *Categorias*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.categoryImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  categoryImage: prismic.ImageField<never>;
}
/**
 * Categorias document from Prismic
 *
 * - **API ID**: `categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoriesDocumentData>,
    "categories",
    Lang
  >;
/** Content for Trabalhos documents */
interface JobsDocumentData {
  /**
   * Titulo do Trabalhos field in *Trabalhos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.jobTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  jobTitle: prismic.KeyTextField;
  /**
   * Imagem Principal field in *Trabalhos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.mainImageJob
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  mainImageJob: prismic.ImageField<never>;
  /**
   * Localização field in *Trabalhos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.jobLocale
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  jobLocale: prismic.KeyTextField;
  /**
   * Data do Trabalho field in *Trabalhos*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.jobDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  jobDate: prismic.DateField;
}
/**
 * Trabalhos document from Prismic
 *
 * - **API ID**: `jobs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<JobsDocumentData>, "jobs", Lang>;
/** Content for Banner Principal documents */
interface MainBannerDocumentData {
  /**
   * Imagem field in *Banner Principal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainBanner.mainImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  mainImage: prismic.ImageField<never>;
}
/**
 * Banner Principal document from Prismic
 *
 * - **API ID**: `mainBanner`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainBannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MainBannerDocumentData>,
    "mainBanner",
    Lang
  >;
export type AllDocumentTypes =
  | CategoriesDocument
  | JobsDocument
  | MainBannerDocument;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      CategoriesDocumentData,
      CategoriesDocument,
      JobsDocumentData,
      JobsDocument,
      MainBannerDocumentData,
      MainBannerDocument,
      AllDocumentTypes,
    };
  }
}
